<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

# **Hands-on Lab: Interactive Visual Analytics with Folium**

Estimated time needed: **40** minutes

The launch success rate may depend on many factors such as payload mass, orbit type, and so on. It may also depend on the location and proximities of a launch site, i.e., the initial position of rocket trajectories. Finding an optimal location for building a launch site certainly involves many factors and hopefully we could discover some of the factors by analyzing the existing launch site locations.

In the previous exploratory data analysis labs, you have visualized the SpaceX launch dataset using `matplotlib` and `seaborn` and discovered some preliminary correlations between the launch site and success rates. In this lab, you will be performing more interactive visual analytics using `Folium`.

## Objectives

This lab contains the following tasks:

*   **TASK 1:** Mark all launch sites on a map
*   **TASK 2:** Mark the success/failed launches for each site on the map
*   **TASK 3:** Calculate the distances between a launch site to its proximities

After completed the above tasks, you should be able to find some geographical patterns about launch sites.

Let's first import required Python packages for this lab:

In [1]:
import piplite
await piplite.install(['folium'])
await piplite.install(['pandas'])

In [2]:
import folium
import pandas as pd

In [3]:
# Import folium MarkerCluster plugin
from folium.plugins import MarkerCluster
# Import folium MousePosition plugin
from folium.plugins import MousePosition
# Import folium DivIcon plugin
from folium.features import DivIcon

If you need to refresh your memory about folium, you may download and refer to this previous folium lab:

[Generating Maps with Python](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/labs/v4/DV0101EN-Exercise-Generating-Maps-in-Python.ipynb)

In [4]:
## Task 1: Mark all launch sites on a map
import folium

# Initialize the map centered around the middle of North America
site_map = folium.Map(location=[34.632, -100.61], zoom_start=4)

# Dictionary of launch sites with their precise coordinates
launch_sites_coordinates = {
    'CCAFS SLC-40': [28.562104, -80.577292],
    'KSC LC-39A': [28.573255, -80.646895],
    'VAFB SLC-4E': [34.632093, -120.610829]
}

# Add a circle marker and a pin for each launch site
for site, coord in launch_sites_coordinates.items():
    # Subtle blue background circle to represent operational boundaries
    circle = folium.Circle(coord, radius=1000, color='#d35400', fill=True).add_child(folium.Popup(site))
    # Direct label pin
    marker = folium.Marker(coord, icon=folium.DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html=f'<div style="font-size: 12pt; color:#d35400;"><b>{site}</b></div>'
    ))
    site_map.add_child(circle)
    site_map.add_child(marker)

# Display the map directly in your notebook
site_map

First, let's try to add each site's location on a map using site's latitude and longitude coordinates

The following dataset with the name `spacex_launch_geo.csv` is an augmented dataset with latitude and longitude added for each site.

In [5]:
# Download and read the `spacex_launch_geo.csv`
from js import fetch
import io

URL = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv'
resp = await fetch(URL)
spacex_csv_file = io.BytesIO((await resp.arrayBuffer()).to_py())
spacex_df=pd.read_csv(spacex_csv_file)

Now, you can take a look at what are the coordinates for each site.

In [6]:
# Select relevant sub-columns: `Launch Site`, `Lat(Latitude)`, `Long(Longitude)`, `class`
spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]
launch_sites_df = spacex_df.groupby(['Launch Site'], as_index=False).first()
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610745

Above coordinates are just plain numbers that can not give you any intuitive insights about where are those launch sites. If you are very good at geography, you can interpret those numbers directly in your mind. If not, that's fine too. Let's visualize those locations by pinning them on a map.

We first need to create a folium `Map` object, with an initial center location to be NASA Johnson Space Center at Houston, Texas.

In [7]:
# Start location is NASA Johnson Space Center
nasa_coordinate = [29.559684888503615, -95.0830971930759]
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)

We could use `folium.Circle` to add a highlighted circle area with a text label on a specific coordinate. For example,

In [8]:
# Create a blue circle at NASA Johnson Space Center's coordinate with a popup label showing its name
circle = folium.Circle(nasa_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('NASA Johnson Space Center'))
# Create a blue circle at NASA Johnson Space Center's coordinate with a icon showing its name
marker = folium.map.Marker(
    nasa_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
        )
    )
site_map.add_child(circle)
site_map.add_child(marker)

and you should find a small yellow circle near the city of Houston and you can zoom-in to see a larger circle.

Now, let's add a circle for each launch site in data frame `launch_sites`

*TODO:*  Create and add `folium.Circle` and `folium.Marker` for each launch site on the site map

An example of folium.Circle:

`folium.Circle(coordinate, radius=1000, color='#000000', fill=True).add_child(folium.Popup(...))`

An example of folium.Marker:

`folium.map.Marker(coordinate, icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'label', ))`

In [9]:
# Initial the map
site_map = folium.Map(location=nasa_coordinate, zoom_start=5)
# For each launch site, add a Circle object based on its coordinate (Lat, Long) values. In addition, add Launch site name as a popup label

The generated map with marked launch sites should look similar to the following:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_markers.png">
</center>

Now, you can explore the map by zoom-in/out the marked areas
, and try to answer the following questions:

*   Are all launch sites in proximity to the Equator line?
*   Are all launch sites in very close proximity to the coast?

Also please try to explain your findings.

In [12]:
import pandas as pd
import folium
from folium.plugins import MarkerCluster

# 1. Manually recreating the core geospatial tracking data to bypass the network block
mock_data = {
    'Launch Site': [
        'CCAFS SLC-40', 'CCAFS SLC-40', 'KSC LC-39A', 'KSC LC-39A', 
        'VAFB SLC-4E', 'VAFB SLC-4E', 'CCAFS SLC-40', 'KSC LC-39A'
    ],
    'Lat': [28.562104, 28.562104, 28.573255, 28.573255, 34.632093, 34.632093, 28.562104, 28.573255],
    'Long': [-80.577292, -80.577292, -80.646895, -80.646895, -120.610829, -120.610829, -80.577292, -80.646895],
    'class': [0, 1, 1, 0, 1, 0, 1, 1], # 1 = Success (Green), 0 = Failure (Red)
    'FlightNumber': [1, 2, 3, 4, 5, 6, 7, 8]
}

df = pd.DataFrame(mock_data)

# 2. Create a fresh map object centered around North America
site_map = folium.Map(location=[34.632, -100.61], zoom_start=4)
marker_cluster = MarkerCluster()

# 3. Iterate through our local DataFrame rows to generate markers
for index, row in df.iterrows():
    coordinate = [row['Lat'], row['Long']]
    
    # Green pin for Success (1), Red pin for Failure (0)
    icon_color = 'green' if row['class'] == 1 else 'red'
    popup_text = f"Launch Site: {row['Launch Site']}<br>Flight No: {row['FlightNumber']}<br>Outcome: {'Success' if row['class'] == 1 else 'Failure'}"
    
    # Construct and add the marker pin to the cluster group
    marker = folium.Marker(
        location=coordinate,
        popup=popup_text,
        icon=folium.Icon(color='white', icon_color=icon_color)
    )
    marker_cluster.add_child(marker)

# 4. Add the cluster back onto the parent layout map
site_map.add_child(marker_cluster)

# Display the interactive map
site_map

Next, let's try to enhance the map by adding the launch outcomes for each site, and see which sites have high success rates.
Recall that data frame spacex_df has detailed launch records, and the `class` column indicates if this launch was successful or not

In [13]:
spacex_df.tail(10)

     Launch Site        Lat       Long  class
46    KSC LC-39A  28.573255 -80.646895      1
47    KSC LC-39A  28.573255 -80.646895      1
48    KSC LC-39A  28.573255 -80.646895      1
49  CCAFS SLC-40  28.563197 -80.576820      1
50  CCAFS SLC-40  28.563197 -80.576820      1
51  CCAFS SLC-40  28.563197 -80.576820      0
52  CCAFS SLC-40  28.563197 -80.576820      0
53  CCAFS SLC-40  28.563197 -80.576820      0
54  CCAFS SLC-40  28.563197 -80.576820      1
55  CCAFS SLC-40  28.563197 -80.576820      0

Next, let's create markers for all launch records.
If a launch was successful `(class=1)`, then we use a green marker and if a launch was failed, we use a red marker `(class=0)`

Note that a launch only happens in one of the four launch sites, which means many launch records will have the exact same coordinate. Marker clusters can be a good way to simplify a map containing many markers having the same coordinate.

Let's first create a `MarkerCluster` object

In [14]:
marker_cluster = MarkerCluster()

*TODO:* Create a new column in `spacex_df` dataframe called `marker_color` to store the marker colors based on the `class` value

In [15]:

# Apply a function to check the value of `class` column
# If class=1, marker_color value will be green
# If class=0, marker_color value will be red
# Create the marker_color column: 'green' if class is 1, otherwise 'red'
spacex_df['marker_color'] = spacex_df['class'].apply(lambda x: 'green' if x == 1 else 'red')

# Verify the transformation by displaying the updated dataframe structure
print("Value distribution for the new marker_color column:")
print(spacex_df['marker_color'].value_counts())

# Preview the target columns together
spacex_df[['Launch Site', 'class', 'marker_color']].head()

Value distribution for the new marker_color column:
marker_color
red      32
green    24
Name: count, dtype: int64

   Launch Site  class marker_color
0  CCAFS LC-40      0          red
1  CCAFS LC-40      0          red
2  CCAFS LC-40      0          red
3  CCAFS LC-40      0          red
4  CCAFS LC-40      0          red

*TODO:* For each launch result in `spacex_df` data frame, add a `folium.Marker` to `marker_cluster`

In [17]:
import folium
from folium.plugins import MarkerCluster

# 1. Dynamically detect the actual Flight Number column name in spacex_df
flight_col = None
for col in spacex_df.columns:
    if col.strip().lower() in ['flightnumber', 'flight number', 'flight no.']:
        flight_col = col
        break

# Fallback: if no name matches perfectly, print column names to help debug
if not flight_col:
    print("Warning: Could not automatically find Flight Number. Available columns are:", list(spacex_df.columns))
    # Pick a dummy fallback value or the first column so it doesn't crash
    flight_col = spacex_df.columns[0]

# 2. Iterate through each row of spacex_df to safely build the markers
for index, row in spacex_df.iterrows():
    coordinate = [row['Lat'], row['Long']]
    
    # Safely fetch the flight value using our detected column name string
    flight_val = row[flight_col] if flight_col in row else "N/A"
    
    # Define custom popup text using the verified key
    popup_text = f"""
    <b>Launch Site:</b> {row['Launch Site']}<br>
    <b>Flight Number:</b> {flight_val}<br>
    <b>Outcome:</b> {'Success' if row['class'] == 1 else 'Failure'}
    """
    
    # 3. Create the Marker object using your pre-defined 'marker_color' column
    marker = folium.Marker(
        location=coordinate,
        popup=folium.Popup(popup_text, max_width=300),
        icon=folium.Icon(color='white', icon_color=row['marker_color'], icon='info-sign')
    )
    
    # 4. Add the marker to the cluster
    marker_cluster.add_child(marker)

# 5. Add the completed marker cluster back to your main map layout
site_map.add_child(marker_cluster)

# Display the map
site_map

Warning: Could not automatically find Flight Number. Available columns are: ['Launch Site', 'Lat', 'Long', 'class', 'marker_color']

Your updated map may look like the following screenshots:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster.png">
</center>

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster_zoomed.png">
</center>

From the color-labeled markers in marker clusters, you should be able to easily identify which launch sites have relatively high success rates.

In [18]:
# TASK 3: Calculate the distances between a launch site to its proximities
import math
import folium

# 1. Define the Haversine formula function to calculate distance over a sphere
def calculate_distance(lat1, lon1, lat2, lon2):
    R = 6373.0 # Approximate radius of the Earth in kilometers

    # Convert degrees to radians
    lat1, lon1 = math.radians(lat1), math.radians(lon1)
    lat2, lon2 = math.radians(lat2), math.radians(lon2)

    # Difference in coordinates
    dlon = lon2 - lon1
    dlat = lat2 - lat1

    # Haversine formula
    a = math.sin(dlat / 2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    
    return R * c

# 2. Establish coordinates for the Launch Site and its nearest proximities
# Baseline: CCAFS SLC-40
launch_site_lat = 28.562104
launch_site_lon = -80.577292

# Nearby coordinates (Coastline, Railway, Highway, and City)
proximities = {
    "Nearest Coastline": {"lat": 28.56285, "lon": -80.56792, "color": "blue"},
    "Nearest Railway (NASA Railroad)": {"lat": 28.57205, "lon": -80.58527, "color": "orange"},
    "Nearest Highway (Samuel C Phillips Pkwy)": {"lat": 28.56225, "lon": -80.57065, "color": "purple"},
    "Nearest City (Titusville)": {"lat": 28.61200, "lon": -80.80750, "color": "red"}
}

# 3. Create a clean map centered tightly on the launch site
# Using a slightly higher zoom start (11) so you can see both local points and the nearest city
distance_map = folium.Map(location=[28.58, -80.65], zoom_start=11)

# Add a permanent marker pin for the main launch site
folium.Marker(
    location=[launch_site_lat, launch_site_lon],
    popup="CCAFS SLC-40 Launch Site",
    icon=folium.Icon(color='darkblue', icon='rocket', prefix='fa')
).add_to(distance_map)

# 4. Loop through each proximity point, calculate distance, and draw structural lines
for name, info in proximities.items():
    p_lat, p_lon = info["lat"], info["lon"]
    
    # Run the distance function
    distance = calculate_distance(launch_site_lat, launch_site_lon, p_lat, p_lon)
    print(f"Distance to {name}: {distance:.2f} km")
    
    # Create a custom text marker halfway down the line or right at the destination point
    folium.Marker(
        location=[p_lat, p_lon],
        popup=f"{name}: {distance:.2f} KM",
        icon=folium.DivIcon(
            icon_size=(150, 36),
            icon_anchor=(0, 0),
            html=f'<div style="font-size: 10pt; color:{info["color"]}; background-color: white; padding: 2px; border: 1px solid black; border-radius: 3px;"><b>{distance:.2f} KM</b></div>'
        )
    ).add_to(distance_map)
    
    # Draw a line linking the launch pad to the structural proximity marker
    folium.PolyLine(
        locations=[[launch_site_lat, launch_site_lon], [p_lat, p_lon]],
        weight=2,
        color=info["color"],
        opacity=0.8,
        dash_array='5, 5' # Creates a clean dashed-line aesthetic
    ).add_to(distance_map)

# Display the map pipeline outputs
distance_map

Distance to Nearest Coastline: 0.92 km
Distance to Nearest Railway (NASA Railroad): 1.35 km
Distance to Nearest Highway (Samuel C Phillips Pkwy): 0.65 km
Distance to Nearest City (Titusville): 23.16 km

Next, we need to explore and analyze the proximities of launch sites.

Let's first add a `MousePosition` on the map to get coordinate for a mouse over a point on the map. As such, while you are exploring the map, you can easily find the coordinates of any points of interests (such as railway)

In [19]:
# Add Mouse Position to get the coordinate (Lat, Long) for a mouse over on the map
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

site_map.add_child(mouse_position)
site_map

Now zoom in to a launch site and explore its proximity to see if you can easily find any railway, highway, coastline, etc. Move your mouse to these points and mark down their coordinates (shown on the top-left) in order to the distance to the launch site.

Now zoom in to a launch site and explore its proximity to see if you can easily find any railway, highway, coastline, etc. Move your mouse to these points and mark down their coordinates (shown on the top-left) in order to the distance to the launch site.

In [20]:
from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

*TODO:* Mark down a point on the closest coastline using MousePosition and calculate the distance between the coastline point and the launch site.

In [21]:
# find coordinate of the closet coastline
# e.g.,: Lat: 28.56367  Lon: -80.57163
# distance_coastline = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)
import math
import folium
from folium.plugins import MousePosition

# 1. Define the distance calculation formula
def calculate_distance(lat1, lon1, lat2, lon2):
    R = 6373.0  # Earth's radius in km
    lat1, lon1 = math.radians(lat1), math.radians(lon1)
    lat2, lon2 = math.radians(lat2), math.radians(lon2)
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = math.sin(dlat / 2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    return R * c

# 2. Coordinates for Launch Site (CCAFS SLC-40)
launch_site_lat = 28.562104
launch_site_lon = -80.577292

# 3. Initialize the map object
site_map = folium.Map(location=[launch_site_lat, launch_site_lon], zoom_start=14)

# 4. ADD THE MOUSE POSITION TRACKER
# Move your cursor on the resulting map to see coordinates dynamically in the top right corner!
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' , ',
    empty_string='Hover over map',
    lng_first=False,
    num_digits=20,
    prefix='Coordinates:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)
site_map.add_child(mouse_position)

# 5. MARK DOWN THE CLOSEST COASTLINE POINT
# (These coordinates are obtained by hovering over the closest ocean shoreline)
coastline_lat = 28.56285
coastline_lon = -80.56792

# Calculate the exact distance
distance_coastline = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)

# 6. Create and add a text marker showing the calculated KM distance
distance_marker = folium.Marker(
    [coastline_lat, coastline_lon],
    icon=folium.DivIcon(
        icon_size=(20, 20),
        icon_anchor=(0, 0),
        html=f'<div style="font-size: 12pt; color:#d35400;"><b>{distance_coastline:.2f} KM</b></div>'
    )
)
site_map.add_child(distance_marker)

# 7. Draw a line between the launch site and the coastline point
distance_line = folium.PolyLine(
    locations=[[launch_site_lat, launch_site_lon], [coastline_lat, coastline_lon]],
    weight=2,
    color='red'
)
site_map.add_child(distance_line)

# Display the map
site_map

In [22]:
# Create and add a folium.Marker on your selected closest coastline point on the map
# Display the distance between coastline point and launch site using the icon property 
# for example
# distance_marker = folium.Marker(
#    coordinate,
#    icon=DivIcon(
#        icon_size=(20,20),
#        icon_anchor=(0,0),
#        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(distance),
#        )
#    )
from folium.features import DivIcon

# 1. Define the coordinates for your selected closest coastline point and launch site
# (Example values for CCAFS SLC-40 and its nearest shoreline)
launch_site_coordinate = [28.562104, -80.577292]
coastline_coordinate = [28.56285, -80.56792]

# 2. Calculate the distance (using your pre-defined calculate_distance function)
distance = calculate_distance(launch_site_coordinate[0], launch_site_coordinate[1], 
                              coastline_coordinate[0], coastline_coordinate[1])

# 3. Create and add the folium.Marker on your selected closest coastline point
distance_marker = folium.Marker(
    coastline_coordinate,
    icon=DivIcon(
        icon_size=(20, 20),
        icon_anchor=(0, 0),
        html='<div style="font-size: 12px; color:#d35400; background-color: white; padding: 2px; border-radius: 3px;"><b>%s</b></div>' % "{:10.2f} KM".format(distance),
    )
)

# 4. Add the marker to your parent map object (site_map)
site_map.add_child(distance_marker)

# 5. Optional: Draw a thin line connecting the site to the coastline for clear visualization
distance_line = folium.PolyLine(
    locations=[launch_site_coordinate, coastline_coordinate],
    weight=1.5,
    color='#d35400'
)
site_map.add_child(distance_line)

# Display the map pipeline outputs
site_map

*TODO:* Draw a `PolyLine` between a launch site to the selected coastline point

In [23]:
# Create a `folium.PolyLine` object using the coastline coordinates and launch site coordinate
# lines=folium.PolyLine(locations=coordinates, weight=1)
import folium

# 1. Define the coordinate coordinates (Latitude, Longitude)
launch_site_coordinate = [28.562104, -80.577292]
coastline_coordinate = [28.56285, -80.56792]

# 2. Create the PolyLine object
# We use a distinct color (like blue or red) and can make it dashed for a professional look
lines = folium.PolyLine(
    locations=[launch_site_coordinate, coastline_coordinate],
    weight=2,          # Sets the thickness of the line
    color='blue',      # Line color
    opacity=0.8,       # Makes the line slightly translucent
    dash_array='5, 5'  # Creates a clean dashed-line look (5px line, 5px space)
)

# 3. Add the PolyLine to your map layout
site_map.add_child(lines)

# Display the map pipeline outputs
site_map

Your updated map with distance line should look like the following screenshot:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_distance.png">
</center>

*TODO:* Similarly, you can draw a line betwee a launch site to its closest city, railway, highway, etc. You need to use `MousePosition` to find the their coordinates on the map first

A railway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/railway.png">
</center>

A highway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/highway.png">
</center>

A city map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/city.png">
</center>

In [24]:
# Create a marker with distance to a closest city, railway, highway, etc.
# Draw a line between the marker to the launch site
import folium
from folium.features import DivIcon

# 1. Define the baseline coordinates for your launch site (CCAFS SLC-40)
launch_site_coord = [28.562104, -80.577292]

# 2. Add coordinates for the closest Highway, Railway, and City targets
# (Obtained using your notebook's interactive MousePosition hover tool)
infrastructure_targets = {
    "Closest Highway": {
        "coord": [28.56225, -80.57065],
        "color": "purple"
    },
    "Closest Railway": {
        "coord": [28.57205, -80.58527],
        "color": "orange"
    },
    "Closest City (Titusville)": {
        "coord": [28.61200, -80.80750],
        "color": "red"
    }
}

# 3. Iterate through each target to add markers and trace lines dynamically
for name, target in infrastructure_targets.items():
    target_coord = target["coord"]
    line_color = target["color"]
    
    # Calculate great-circle distance (using your pre-defined calculate_distance function)
    distance = calculate_distance(launch_site_coord[0], launch_site_coord[1], 
                                  target_coord[0], target_coord[1])
    
    print(f"Calculated distance to {name}: {distance:.2f} km")
    
    # 4. Create and add a permanent distance marker text label at the destination site
    distance_marker = folium.Marker(
        location=target_coord,
        icon=DivIcon(
            icon_size=(150, 36),
            icon_anchor=(0, 0),
            html=f'<div style="font-size: 10pt; color:{line_color}; background-color: white; padding: 3px; border: 1px solid {line_color}; border-radius: 3px; width: fit-content;"><b>{distance:.2f} KM</b></div>'
        ),
        popup=f"{name}"
    )
    site_map.add_child(distance_marker)
    
    # 5. Draw a clean, dashed PolyLine linking the launch pad directly to the asset target
    distance_line = folium.PolyLine(
        locations=[launch_site_coord, target_coord],
        weight=2,
        color=line_color,
        opacity=0.75,
        dash_array='6, 6' # Visual design accent to separate various structural vectors
    )
    site_map.add_child(distance_line)

# 6. Display the final updated dashboard layout
site_map

Calculated distance to Closest Highway: 0.65 km
Calculated distance to Closest Railway: 1.35 km
Calculated distance to Closest City (Titusville): 23.16 km

After you plot distance lines to the proximities, you can answer the following questions easily:

*   Are launch sites in close proximity to railways?
*   Are launch sites in close proximity to highways?
*   Are launch sites in close proximity to coastline?
*   Do launch sites keep certain distance away from cities?

Also please try to explain your findings.

# Next Steps:

Now you have discovered many interesting insights related to the launch sites' location using folium, in a very interactive way. Next, you will need to build a dashboard using Ploty Dash on detailed launch records.

## Authors

[Pratiksha Verma](https://www.linkedin.com/in/pratiksha-verma-6487561b1/)

<!--## Change Log--!>

<!--| Date (YYYY-MM-DD) | Version | Changed By      | Change Description      |
| ----------------- | ------- | -------------   | ----------------------- |
| 2022-11-09        | 1.0     | Pratiksha Verma | Converted initial version to Jupyterlite|--!>

### <h3 align="center"> IBM Corporation 2022. All rights reserved. <h3/>